Week7.Master.MVC/Controllers/CorsiController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Week7.Master.Core.BusinessLayer;
using Week7.Master.MVC.Helper;
using Week7.Master.MVC.Models;

namespace Week7.Master.MVC.Controllers
{
    public class CorsiController : Controller
    {
        private readonly IBusinessLayer BL;

        public CorsiController(IBusinessLayer bl)
        {
            BL = bl;
        }

        //CRUD su Corso

        //utl : https.../Corsi
        [HttpGet]
        public IActionResult Index()
        {
            var corsi = BL.GetAllCorsi();

            List<CorsoViewModel> corsiViewModel = new List<CorsoViewModel>();

            foreach(var item in corsi)
            {
                corsiViewModel.Add(item.toCorsoViewModel());
            }

            return View(corsiViewModel);
        }

        //url: https.../Corsi/Details/id
        [HttpGet("Corsi/Details/{code}")] //lo specifico visto che ho cod, se dovessi avere id non sarebbe necessario
        public IActionResult Details(string code)
        {
            var corso = BL.GetAllCorsi().FirstOrDefault(c=> c.CorsoCodice == code);
            var corsoViewModel = corso.toCorsoViewModel();

            return View(corsoViewModel);
        }

        //add
        [Authorize(Policy = "Adm")] //non solo chiede il login/autenticazione ma richiede che il ruolo sia Administrator        
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Policy = "Adm")] //non solo chiede il login/autenticazione ma richiede che il ruolo sia Administrator        
        [HttpPost]
        public IActionResult Create(CorsoViewModel corsoViewModel)
        {
            if(ModelState.IsValid) //se la validazione è andata a buon fine, aggiungo alla lista e torno alla Index
            {
                BL.InserisciNuovoCorso(corsoViewModel.toCorso());
                return RedirectToAction(nameof(Index)); //qui mi rimandi alla index
            }
            return View(corsoViewModel); //se non va a buon fine, ritorno 
        }

        //Edit
        [Authorize(Policy = "Adm")] //non solo chiede il login/autenticazione ma richiede che il ruolo sia Administrator        
        [HttpGet("Corsi/Edit/{code}")]
        public IActionResult Edit(string code)
        {
            var corso = BL.GetAllCorsi().FirstOrDefault(c => c.CorsoCodice == code);
            var corsoViewModel = corso.toCorsoViewModel();
            return View(corsoViewModel);
        }

        [Authorize(Policy = "Adm")] //non solo chiede il login/autenticazione ma richiede che il ruolo sia Administrator        
        [HttpPost("Corsi/Edit/{code}")]
        public IActionResult Edit(CorsoViewModel corsoViewModel)
        {
            var corso = corsoViewModel.toCorso();

            if (ModelState.IsValid) //se la validazione è andata a buon fine, aggiungo alla lista e torno alla Index
            {
                BL.ModificaCorso(corso.CorsoCodice,corso.Nome,corso.Descrizione);
                return RedirectToAction(nameof(Index)); //qui mi rimandi alla index
            }
            return View(corsoViewModel); //se non va a buon fine, ritorno 
        }

        //Delete
        [Authorize(Policy = "Adm")] //non solo chiede il login/autenticazione ma richiede che il ruolo sia Administrator        
        [HttpGet]
        public IActionResult Delete(string id)
        {
            var corso = BL.GetAllCorsi().FirstOrDefault(c => c.CorsoCodice == id);
            var corsoViewModel = corso.toCorsoViewModel();
            return View(corsoViewModel);
        }

        [Authorize(Policy = "Adm")] //non solo chiede il login/autenticazione ma richiede che il ruolo sia Administrator        
        [HttpPost]
        public IActionResult Delete(CorsoViewModel corsoViewModel)
        {
            var corso = corsoViewModel.toCorso();

            if (ModelState.IsValid) //se la validazione è andata a buon fine, aggiungo alla lista e torno alla Index
            {
                BL.DeleteByCode(corso.CorsoCodice);
                return RedirectToAction(nameof(Index)); //qui mi rimandi alla index
            }
            return View(corsoViewModel); //se non va a buon fine, ritorno 
        }
    }
}

Week7.Master.MVC/Controllers/CounterController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Week7.Master.MVC.Models;

namespace Week7.Master.MVC.Controllers
{
    public class CounterController : Controller
    {
        private readonly ICounterService counterService;
        private readonly ICounterService counterService2;

        public CounterController(ICounterService counterService, ICounterService counterService2)
        {
            this.counterService = counterService;
            this.counterService2 = counterService2;
        }

        public IActionResult Index()
        {
            var a = counterService.Count();
            var b = counterService2.Count();

            CounterViewModel c = new CounterViewModel { A = a, B = b };
            return View(c);
        }
    }
}

Week7.Master.MVC/Controllers/StudentiController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Week7.Master.Core.BusinessLayer;
using Week7.Master.MVC.Helper;
using Week7.Master.MVC.Models;

namespace Week7.Master.MVC.Controllers
{
    [Authorize(Policy = "Adm")]
    public class StudentiController : Controller
    {
        private readonly IBusinessLayer BL;

        public StudentiController(IBusinessLayer bl)
        {
            BL = bl;
        }
        public IActionResult Index()
        {
            var studenti = BL.GetAllStudenti();
            List<StudenteViewModel> studentiViewModel = new List<StudenteViewModel>();

            foreach (var item in studenti)
            {
                studentiViewModel.Add(item?.toStudenteViewModel());
            }
            return View(studentiViewModel);
        }

        [HttpGet] 
        public IActionResult Details(int id)
        {
            var studente = BL.GetAllStudenti().FirstOrDefault(s=> s.Id == id);
            var studenteViewModel = studente.toStudenteViewModel();

            return View(studenteViewModel);
        }

        //add

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(StudenteViewModel studenteViewModel)
        {
            if (ModelState.IsValid) //se la validazione è andata a buon fine, aggiungo alla lista e torno alla Index
            {
                var studente = studenteViewModel.toStudente();
                //studente.CorsoCodice = "C-01";
                BL.AggiungiStudente(studente);
                return RedirectToAction(nameof(Index)); //qui mi rimandi alla index
            }
            return View(studenteViewModel); //se non va a buon fine, ritorno 
        }

        //Edit
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var studente = BL.GetAllStudenti().FirstOrDefault(s => s.Id == id);
            var studenteViewModel = studente.toStudenteViewModel();
            return View(studenteViewModel);
        }

        [HttpPost]
        public IActionResult Edit(StudenteViewModel studenteViewModel)
        {
            var studente = studenteViewModel.toStudente();

            if (ModelState.IsValid) //se la validazione è andata a buon fine, aggiungo alla lista e torno alla Index
            {
                BL.ModificaStudente(studenteViewModel.Id, studenteViewModel.Nome, studenteViewModel.Cognome, studenteViewModel.DataNascita, studenteViewModel.TitoloStudio, studenteViewModel.Email, studenteViewModel.CorsoCodice);
                return RedirectToAction(nameof(Index)); //qui mi rimandi alla index
            }
            return View(studenteViewModel); //se non va a buon fine, ritorno 
        }

        //Delete
        public IActionResult Delete(int id)
        {
            var studente = BL.GetAllStudenti().FirstOrDefault(s => s.Id == id);
            var studenteViewModel = studente.toStudenteViewModel();
            return View(studenteViewModel);
        }

        [HttpPost]
        public IActionResult Delete(StudenteViewModel studenteViewModel)
        {
            var studente = studenteViewModel.toStudente();

            if (ModelState.IsValid)
            {
                BL.DeleteStudentById(studenteViewModel.Id);
                return RedirectToAction(nameof(Index));
            }
            return View(studenteViewModel);
        }

        [HttpGet]
        public IActionResult DeleteJS(int id)
        {
            var messaggio = BL.DeleteStudentById(id);
            if (messaggio == "Studente eliminato correttamente")
            {
                return Json(true);
            }

            return Json(false);
        }
        private void LoadViewBag()
        {
            ViewBag.TitoloStudio = new SelectList(new[]{
                new { Value="D", Text="Diploma"},
                new { Value="L", Text="Laurea"} }.OrderBy(x => x.Text), "Value", "Text");
        }
    }
}

Week7.Master.MVC/Controllers/UtentiController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Week7.Master.Core.BusinessLayer;
using Week7.Master.MVC.Models;

namespace Week7.Master.MVC.Controllers
{
    public class UtentiController : Controller
    {
        private readonly IBusinessLayer BL; //per collegarsi alle logiche di business

        public UtentiController(IBusinessLayer bl)
        {
            BL = bl; //o con this
        }

        [HttpGet]
        public IActionResult Login(string returnUrl)
        {
            return View(new UtenteLoginViewModel
            {
                ReturnUrl = returnUrl
            });
        }


        [HttpPost]
        public async Task<IActionResult> LoginAsync(UtenteLoginViewModel utenteLoginViewModel)
        {
            if (utenteLoginViewModel == null)
            {
                return View();
            }

            var utente = BL.GetAccount(utenteLoginViewModel.Username);
            if (utente != null && ModelState.IsValid)
            {
                if (utente.Password == utenteLoginViewModel.Password)
                {
                    //l'utente è autenticato

                    var claim = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, utente.Nome),
                        new Claim(ClaimTypes.Role, utente.Ruolo.ToString())
                    };

                    var properties = new AuthenticationProperties
                    {
                        ExpiresUtc = DateTimeOffset.UtcNow.AddHours(1), // logout dopo un'ora di inattività
                        RedirectUri = utenteLoginViewModel.ReturnUrl
                    };
                    var claimIdentity = new ClaimsIdentity(claim, CookieAuthenticationDefaults.AuthenticationScheme);

                    await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(claimIdentity),
                        properties
                        );
                    return Redirect("/");
                }
                else
                {
                    ModelState.AddModelError(nameof(utenteLoginViewModel.Password), "Password errata");
                    return View(utenteLoginViewModel);
                }
            }
            //else
            //{
            //    return View();
            //}
            return View();
        }

        public async Task<IActionResult> LogoutAsync()
        {
            await HttpContext.SignOutAsync();
            return Redirect("/");
        }

        public IActionResult Forbidden() => View();
        //{
        //    return View();
        //}
    }
}

Week7.Master.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Master.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Master.MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if (User.Identity.IsAuthenticated)
                {
                    var name = ((System.Security.Claims.ClaimsIdentity)User.Identity).Claims.First(x => x.Type == System.Security.Claims.ClaimTypes.Name).Value;
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Prova">Prova</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Corsi" asp-action="Index">Corsi</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Studenti" asp-action="Index">Studenti</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Counter" asp-action="Index">Counter</a>
                            </li>
                            @*<li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Utenti" asp-action="Login">Login</a>
                    </li>*@
                        </ul>
                    </div>
                    <strong>Bentornato @name!</strong>
                    <a asp-controller="Utenti" asp-action="Logout">Logout</a>
                }
                else
                {
                    <a asp-controller="Utenti" asp-action="Login">Login</a>
                }
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Master.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>