Week7.Master.MVC/Controllers/DocentiController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Week7.Master.Core.BusinessLayer;
using Week7.Master.MVC.Helper;
using Week7.Master.MVC.Models;

namespace Week7.Master.MVC.Controllers
{
    public class DocentiController : Controller
    {
        private readonly IBusinessLayer BL;

        public DocentiController(IBusinessLayer bl)
        {
            BL = bl;
        }
        public IActionResult Index()
        {
            var docenti = BL.GetAllDocenti();
            List<DocenteViewModel> docentiViewModel = new List<DocenteViewModel>();

            foreach (var item in docenti)
            {
                docentiViewModel.Add(item.toDocenteViewModel());
            }
            return View(docentiViewModel);
        }

        [HttpGet] //lo specifico visto che ho cod, se dovessi avere id non sarebbe necessario
        public IActionResult Details(int id)
        {
            var docente = BL.GetAllDocenti().FirstOrDefault(d => d.Id == id);
            var docenteViewModel = docente.toDocenteViewModel();

            return View(docenteViewModel);
        }

        //add

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(DocenteViewModel docenteViewModel)
        {
            if (ModelState.IsValid) //se la validazione è andata a buon fine, aggiungo alla lista e torno alla Index
            {
                BL.AggiungiDocente(docenteViewModel.toDocente());
                return RedirectToAction(nameof(Index)); //qui mi rimandi alla index
            }
            return View(docenteViewModel); //se non va a buon fine, ritorno 
        }

        //Edit
        [HttpGet]
        public IActionResult Edit(int id)
        {
            var docente = BL.GetAllDocenti().FirstOrDefault(d => d.Id == id);
            var docenteViewModel = docente.toDocenteViewModel();
            return View(docenteViewModel);
        }

        [HttpPost]
        public IActionResult Edit(DocenteViewModel docenteViewModel)
        {
            var docente = docenteViewModel.toDocente();

            if (ModelState.IsValid) //se la validazione è andata a buon fine, aggiungo alla lista e torno alla Index
            {
                BL.ModificaDocente(docenteViewModel.Id, docenteViewModel.Nome, docenteViewModel.Cognome, docenteViewModel.Email, docenteViewModel.Telefono);
                return RedirectToAction(nameof(Index)); //qui mi rimandi alla index
            }
            return View(docenteViewModel); //se non va a buon fine, ritorno 
        }

        //Delete
        public IActionResult Delete(int id)
        {
            var docente = BL.GetAllDocenti().FirstOrDefault(d => d.Id == id);
            var docenteViewModel = docente.toDocenteViewModel();
            return View(docenteViewModel);
        }

        [HttpPost]
        public IActionResult Delete(DocenteViewModel docenteViewModel)
        {
            var docente = docenteViewModel.toDocente();

            if (ModelState.IsValid) 
            {
                BL.DeleteDocenteById(docenteViewModel.Id);
                return RedirectToAction(nameof(Index));
            }
            return View(docenteViewModel);  
        }
    }
}

Week7.Master.MVC/Views/Docenti/Create.cshtml
@model DocenteViewModel
<h1>Inserisci nuovo Docente</h1>

<form method="post">
    <div class="mb-3">
        <label asp-for="Nome" class="form-label"></label>
        <input type="text" class="form-control" asp-for="Nome" placeholder="Inserisci nome docente">
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Cognome" class="form-label"></label>
        <input type="text" class="form-control" asp-for="Cognome" placeholder="Inserisci Cognome">
        <span asp-validation-for="Cognome" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label"></label>
        <input type="text" class="form-control" asp-for="Email" placeholder="Inserisci email ">
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Telefono" class="form-label"></label>
        <input type="text" class="form-control" asp-for="Telefono" placeholder="Inserisci Telefono ">
        <span asp-validation-for="Telefono" class="text-danger"></span>
    </div>

    <input type="submit" value="Inserisci" class="btn btn-primary" />
    <input type="reset" value="Reset" class="btn btn-danger" />
    <a class="btn btn-primary" asp-action="Index" role="button">Back</a>
</form>

Week7.Master.MVC/Views/Docenti/Delete.cshtml
@model DocenteViewModel


<form method="post">
    <p>Sei sicuro di voler eliminare il docente ?</p>

    <div class="form-group">
        <label asp-for="Nome"></label>
        <input asp-for="Nome" class="form-control" readonly />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Cognome" class="form-label"></label>
        <input asp-for="Cognome" class="form-control" readonly />
        <span asp-validation-for="Cognome" class="text-danger"></span>
    </div>

    <input type="submit" value="Conferma" class="btn btn-danger" />
    <a class="btn btn-primary" asp-action="Index" role="button">Back</a>
</form>

Week7.Master.MVC/Views/Docenti/Details.cshtml
@model DocenteViewModel

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Nome</th>
            <th scope="col">Email</th>
            <th scope="col">Telefono</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.Nome</td>
            <td>@Model.Email</td>
            <td>@Model.Telefono</td>
        </tr>
    </tbody>
</table>

Week7.Master.MVC/Views/Docenti/Edit.cshtml
@model DocenteViewModel
<h1>Modifica Docente</h1>

<form method="post">
    <div class="mb-3" style="visibility: hidden;">
        <label asp-for="Nome"></label>
        <input asp-for="Nome" class="form-control" />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Cognome" class="form-label"></label>
        <input type="text" class="form-control" asp-for="Cognome" placeholder="Inserisci Cognome">
        <span asp-validation-for="Cognome" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Email" class="form-label"></label>
        <input type="text" class="form-control" asp-for="Email" placeholder="Inserisci email ">
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="mb-3">
        <label asp-for="Telefono" class="form-label"></label>
        <input type="text" class="form-control" asp-for="Telefono" placeholder="Inserisci Telefono ">
        <span asp-validation-for="Telefono" class="text-danger"></span>
    </div>

    <input type="submit" value="Inserisci" class="btn btn-primary" />
    <input type="reset" value="Reset" class="btn btn-danger" />
    <a class="btn btn-primary" asp-action="Index" role="button">Back</a>
</form>

Week7.Master.MVC/Views/Docenti/Index.cshtml
@model List<DocenteViewModel>

<h1>Ecco la lista dei Docenti</h1>
<a class="btn btn-primary" asp-controller="Docenti" asp-action="Create" type="button">Inserisci nuovo docente</a>

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Nome</th>
            <th scope="col">Cognome</th>
            @*<th scope="col">Descrizione</th>*@
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Nome</td>
                <td>@item.Cognome</td>
                @*<td>@item.Descrizione</td>*@
            <td>
                <a asp-controller="Docenti" asp-action="Details" asp-route-id="@item.Id" class="btn btn-secondary">Visualizza dettagli docente</a>
                <a asp-controller="Docenti" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Modifica docente</a>
                <a asp-controller="Docenti" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Elimina docente</a>
            </td>
            </tr>
        }
    </tbody>
</table>